In [1]:
import numpy as np
import yaml
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable

In [2]:
# Function to read expert data

def read_data(datasets_dir="./data", frac = 0.1, dataset_1 = True):
    print("... read data")
    
    if dataset_1: 
        data_file = os.path.join(datasets_dir, 'transitions.pkl')
        data = np.load(data_file, allow_pickle=True)
        X = [data[i][j][0] for i in range(len(data)) for j in range(len(data[i]))]
        y = [data[i][j][1] for i in range(len(data)) for j in range(len(data[i]))]
        states = torch.cat(X).to(torch.float32)
        actions = torch.cat(y).to(torch.float32)
    else:
        data_file = os.path.join(datasets_dir, 'cart_pole_demonstrations.yaml')
        with open(data_file, 'r') as file:
            data = yaml.safe_load(file)
        X = np.array(data['observations'])
        y = np.array(data['actions']).reshape(-1, 1)
        states = torch.from_numpy(X).to(torch.float32)
        actions = torch.from_numpy(y).to(torch.float32)
    print(states.shape)
    print(actions.shape)    
    return states, actions

read_data()

... read data
torch.Size([20000, 4])
torch.Size([20000, 1])


(tensor([[-0.0227,  0.0431,  0.0228, -0.0495],
         [-0.0218, -0.1524,  0.0218,  0.2503],
         [-0.0249,  0.0424,  0.0268, -0.0354],
         ...,
         [-0.0908, -0.2321, -0.0044,  0.3062],
         [-0.0954, -0.0369,  0.0017,  0.0121],
         [-0.0962,  0.1581,  0.0020, -0.2801]]),
 tensor([[0.],
         [1.],
         [1.],
         ...,
         [1.],
         [1.],
         [0.]]))

In [3]:
# read data 

states, actions = read_data()
print(f"States: {states}, Actions: {actions}")



... read data
torch.Size([20000, 4])
torch.Size([20000, 1])
States: tensor([[-0.0227,  0.0431,  0.0228, -0.0495],
        [-0.0218, -0.1524,  0.0218,  0.2503],
        [-0.0249,  0.0424,  0.0268, -0.0354],
        ...,
        [-0.0908, -0.2321, -0.0044,  0.3062],
        [-0.0954, -0.0369,  0.0017,  0.0121],
        [-0.0962,  0.1581,  0.0020, -0.2801]]), Actions: tensor([[0.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [0.]])


In [4]:
# Visualize the data as panda's data frame

import pandas as pd
data= pd.DataFrame({"X1": states[:, 0], "X2": states[:, 1], "X3": states[:, 2], "X4": states[:, 3], "action": actions.flatten()})


data.head(10)

X1        X2        X3        X4  action
0 -0.022675  0.043077  0.022810 -0.049454     0.0
1 -0.021814 -0.152365  0.021821  0.250337     1.0
2 -0.024861  0.042439  0.026827 -0.035384     1.0
3 -0.024012  0.237166  0.026120 -0.319483     0.0
4 -0.019269  0.041682  0.019730 -0.018679     1.0
5 -0.018435  0.236516  0.019357 -0.305072     0.0
6 -0.013705  0.041123  0.013255 -0.006348     1.0
7 -0.012882  0.236053  0.013128 -0.294820     0.0
8 -0.008161  0.040746  0.007232  0.001975     1.0
9 -0.007346  0.235764  0.007271 -0.288418     0.0

In [5]:
data.action.value_counts()

0.0    10004
1.0     9996
Name: action, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split(states, actions, test_size=0.2, random_state=42)

len(X_train), len(X_test), len(y_train), len(y_test)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

torch.Size([16000, 4])
torch.Size([16000, 1])
torch.Size([4000, 4])
torch.Size([4000, 1])


In [7]:
import torch
from torch import nn

device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [8]:
class StateActionModel(nn.Module):

    def __init__(self,
                 input_size: int = 4,
                 hiddenLayer1_size: int = 128,
                 hiddenLayer2_size: int = 128,                 
                 output_size: int = 1) -> None: 
        
        super(StateActionModel, self).__init__()
        self.hiddenLayer1 = nn.Linear(in_features= input_size,
                             out_features= hiddenLayer1_size)
        self.hiddenLayer2 = nn.Linear(in_features= hiddenLayer1_size,
                             out_features= hiddenLayer2_size)
        self.output = nn.Linear(in_features= hiddenLayer2_size,
                             out_features= output_size)        
    def forward(self, x):
        x = F.tanh(self.hiddenLayer1(x))
        x = F.tanh(self.hiddenLayer2(x))
        x = self.output(x)
        return x

In [9]:
model = StateActionModel().to(device)
model

StateActionModel(
  (hiddenLayer1): Linear(in_features=4, out_features=128, bias=True)
  (hiddenLayer2): Linear(in_features=128, out_features=128, bias=True)
  (output): Linear(in_features=128, out_features=1, bias=True)
)

In [10]:
# Make predictions with the model
untrained_preds = model(X_test.to(device))
print(f"Length of predictions: {len(untrained_preds)}, Shape: {untrained_preds.shape}")
print(f"Length of test samples: {len(y_test)}, Shape: {y_test.shape}")
print(f"\nFirst 10 predictions:\n{untrained_preds[:10]}")
print(f"\nFirst 10 test labels:\n{y_test[:10]}")

Length of predictions: 4000, Shape: torch.Size([4000, 1])
Length of test samples: 4000, Shape: torch.Size([4000, 1])

First 10 predictions:
tensor([[-0.0955],
        [-0.1196],
        [-0.0876],
        [-0.0945],
        [-0.1020],
        [-0.1367],
        [-0.0972],
        [-0.0955],
        [-0.0683],
        [-0.1169]], device='cuda:0', grad_fn=<SliceBackward0>)

First 10 test labels:
tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])


/home/damnghost/miniconda3/envs/dlrv/lib/python3.8/site-packages/torch/nn/functional.py:1933: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [11]:
# Create a loss function
# loss_fn = nn.BCELoss() # BCELoss = no sigmoid built-in
loss_fn = nn.BCEWithLogitsLoss() # BCEWithLogitsLoss = sigmoid built-in

# Create an optimizer
optimizer = torch.optim.Adam(params=model.parameters(), 
                            lr=0.001)

In [12]:
# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100 
    return acc

In [13]:
# View the frist 5 outputs of the forward pass on the test data
y_logits = model(X_test.to(device))
y_logits

tensor([[-0.0955],
        [-0.1196],
        [-0.0876],
        ...,
        [-0.0396],
        [-0.0920],
        [-0.0875]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [14]:
# Find the predicted labels (round the prediction probabilities)
y_preds = torch.round(y_logits)
print(f"predictions: {y_preds}")

# In full
y_pred_labels = torch.round((model(X_test.to(device))))

# Check for equality
print(torch.eq(y_preds.squeeze(), y_pred_labels.squeeze()))

# Get rid of extra dimension
y_preds.squeeze()

predictions: tensor([[-0.],
        [-0.],
        [-0.],
        ...,
        [-0.],
        [-0.],
        [-0.]], device='cuda:0', grad_fn=<RoundBackward0>)
tensor([True, True, True,  ..., True, True, True], device='cuda:0')


tensor([-0., -0., -0.,  ..., -0., -0., -0.], device='cuda:0',
       grad_fn=<SqueezeBackward0>)

In [15]:
y_test

tensor([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [0.],
        [1.]])

In [16]:
torch.manual_seed(42)

epochs = 1000 # Train for longer

# Put data to target device
X_train, y_train = X_train.to(device), y_train.to(device)
X_test, y_test = X_test.to(device), y_test.to(device)

model.train()
for epoch in range(epochs):
    ### Training
    # 1. Forward pass
    y_logits = model(X_train)
    y_pred = torch.round(torch.sigmoid(y_logits)) # logits -> predicition probabilities -> prediction labels

    # 2. Calculate loss/accuracy
    loss = loss_fn(y_logits, y_train)
    acc = accuracy_fn(y_true=y_train, 
                      y_pred=y_pred)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Loss backwards
    loss.backward()

    # 5. Optimizer step
    optimizer.step()

    ### Testing
    model.eval()
    with torch.inference_mode():
        # 1. Forward pass
        test_logits = model(X_test)
        test_pred = torch.round(torch.sigmoid(test_logits))
        # 2. Caculate loss/accuracy
        test_loss = loss_fn(test_logits,
                            y_test)
        test_acc = accuracy_fn(y_true=y_test,
                               y_pred=test_pred)

    # Print out what's happening every 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f}, Accuracy: {acc:.2f}% | Test loss: {test_loss:.5f}, Test acc: {test_acc:.2f}%")


Epoch: 0 | Loss: 0.69935, Accuracy: 49.86% | Test loss: 0.68462, Test acc: 50.68%
Epoch: 10 | Loss: 0.56962, Accuracy: 77.53% | Test loss: 0.55525, Test acc: 78.25%
Epoch: 20 | Loss: 0.45715, Accuracy: 78.59% | Test loss: 0.44448, Test acc: 79.80%
Epoch: 30 | Loss: 0.38313, Accuracy: 79.62% | Test loss: 0.37569, Test acc: 80.30%
Epoch: 40 | Loss: 0.34916, Accuracy: 80.38% | Test loss: 0.34663, Test acc: 80.35%
Epoch: 50 | Loss: 0.33791, Accuracy: 80.33% | Test loss: 0.33789, Test acc: 80.62%
Epoch: 60 | Loss: 0.33403, Accuracy: 80.52% | Test loss: 0.33413, Test acc: 80.90%
Epoch: 70 | Loss: 0.33178, Accuracy: 80.66% | Test loss: 0.33152, Test acc: 80.88%
Epoch: 80 | Loss: 0.32972, Accuracy: 80.80% | Test loss: 0.32953, Test acc: 81.15%
Epoch: 90 | Loss: 0.32756, Accuracy: 80.93% | Test loss: 0.32752, Test acc: 81.27%
Epoch: 100 | Loss: 0.32530, Accuracy: 81.09% | Test loss: 0.32518, Test acc: 81.38%
Epoch: 110 | Loss: 0.32294, Accuracy: 81.31% | Test loss: 0.32280, Test acc: 81.47%
Epo

Epoch: 980 | Loss: 0.12529, Accuracy: 95.34% | Test loss: 0.11351, Test acc: 95.67%
Epoch: 990 | Loss: 0.12505, Accuracy: 95.35% | Test loss: 0.11325, Test acc: 95.67%


In [17]:
torch.save(model.state_dict(), os.path.join("model_0.pkl"))
print("Model saved in file")

Model saved in file


In [19]:


from __future__ import print_function

from datetime import datetime
import numpy as np
import gym
import os
import json
import torch


def run_episode(env, agent, rendering=True, max_timesteps=1000):
    
    episode_reward = 0
    step = 0

    state = env.reset()
    while True:

#         get action
        agent.eval()
        tensor_state = torch.from_numpy(state)
        tensor_action = agent(tensor_state)
        a = torch.round(torch.sigmoid(tensor_action)).squeeze().to(torch.int).detach().numpy()
#         a = np.random.randint(0, 1)
        next_state, r, done, info = env.step(a)   
        episode_reward += r       
        state = next_state
        step += 1
#         print(step)
        
        if rendering:
            env.render()

        if done or step > max_timesteps: 
            break

    return episode_reward


if __name__ == "__main__":

    # important: don't set rendering to False for evaluation (you may get corrupted state images from gym)
    rendering = True                      
    
    n_test_episodes = 100                  # number of episodes to test

    # load agent
    agent = StateActionModel()
    agent.load_state_dict(torch.load("model_0.pkl"))

    env = gym.make('CartPole-v0')
    print(env.spec.max_episode_steps)
    print(env.spec.reward_threshold)

    episode_rewards = []
    for i in range(n_test_episodes):
        episode_reward = run_episode(env, agent, rendering=rendering)
        episode_rewards.append(episode_reward)

    # save results in a dictionary and write them into a .json file
    results = dict()
    results["episode_rewards"] = episode_rewards
    results["mean"] = np.array(episode_rewards).mean()
    results["std"] = np.array(episode_rewards).std()
    print(results)
            
    env.close()
    print('... finished')

200
195.0
{'episode_rewards': [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0], 'mean': 200.0, 'std': 0.0}
... finished
